In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [4]:
z=torch.FloatTensor([1,2,3])
hypothesis=F.softmax(z, dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [5]:
hypothesis.sum()

tensor(1.)

In [16]:
z=torch.randn(3,5, requires_grad=True)
hypothesis=F.softmax(z, dim=1)
print(hypothesis)

tensor([[0.3750, 0.1275, 0.0732, 0.2069, 0.2174],
        [0.2843, 0.0757, 0.3436, 0.0719, 0.2244],
        [0.2725, 0.0887, 0.1172, 0.3846, 0.1370]], grad_fn=<SoftmaxBackward>)


In [17]:
y=torch.randint(5, (3,)).long()
print(y)

tensor([1, 1, 0])


In [19]:
y_one_hot=torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1),1)

tensor([[0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])

In [24]:
cost=(y_one_hot * -torch.log(F.softmax(z, dim=1))).sum(dim=1).mean()
cost=(y_one_hot * -F.log_softmax(z, dim=1)).sum(dim=1).mean()
cost=F.nll_loss(F.log_softmax(z, dim=1), y)
F.cross_entropy(z,y)
print(cost)

tensor(1.9801, grad_fn=<NllLossBackward>)


In [42]:
x_train = [[1, 2, 1, 1],
        [2, 1, 3, 2],
        [3, 1, 3, 4],
        [4, 1, 5, 5],
        [1, 7, 5, 5],
        [1, 2, 5, 6],
        [1, 6, 6, 6],
        [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)
y_train

tensor([2, 2, 2, 1, 1, 1, 0, 0])

In [46]:
W = torch.zeros((4,3), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
optimizer = optim.SGD([W, b], lr=0.1)
nb_epochs=1000
for epoch in range(nb_epochs+1):
    hypothesis=F.softmax(x_train.matmul(W) + b, dim=1)
    y_one_hot=torch.zeros_like(hypothesis)
    y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)
    cost=(y_one_hot * -torch.log(F.softmax(hypothesis, dim=1))).sum(dim=1).mean()
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{}, Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
        
        ))

Epoch    0/1000, Cost: 1.098612
Epoch  100/1000, Cost: 0.901535
Epoch  200/1000, Cost: 0.839114
Epoch  300/1000, Cost: 0.807826
Epoch  400/1000, Cost: 0.788472
Epoch  500/1000, Cost: 0.774822
Epoch  600/1000, Cost: 0.764449
Epoch  700/1000, Cost: 0.756191
Epoch  800/1000, Cost: 0.749398
Epoch  900/1000, Cost: 0.743671
Epoch 1000/1000, Cost: 0.738749


In [49]:
W = torch.zeros((4,3), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
optimizer=optim.SGD([W,b], lr=0.1)
nb_epochs=1000
for epoch in range(nb_epochs+1):
    z=x_train.matmul(W)+b
    cost=F.cross_entropy(z, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch %100==0:
        print('Epoch : {:4d}/{}, Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
        
        ))

Epoch :    0/1000, Cost: 1.098612
Epoch :  100/1000, Cost: 0.761050
Epoch :  200/1000, Cost: 0.689991
Epoch :  300/1000, Cost: 0.643229
Epoch :  400/1000, Cost: 0.604117
Epoch :  500/1000, Cost: 0.568255
Epoch :  600/1000, Cost: 0.533922
Epoch :  700/1000, Cost: 0.500291
Epoch :  800/1000, Cost: 0.466908
Epoch :  900/1000, Cost: 0.433506
Epoch : 1000/1000, Cost: 0.399962


In [60]:
class SoftmaxClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(4,3)
    def forward(self, x):
        return self.linear(x)
model=SoftmaxClassifierModel()

optimizer=optim.SGD(model.parameters(), lr=0.1)
nb_epochs=1000
for epoch in range(nb_epochs+1):
    prediction=model(x_train)
    cost=F.cross_entropy(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch %100 ==0:
        print('Epoch {:4d}/{}, Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
        
        ))

Epoch    0/1000, Cost: 1.961228
Epoch  100/1000, Cost: 0.715961
Epoch  200/1000, Cost: 0.639964
Epoch  300/1000, Cost: 0.584711
Epoch  400/1000, Cost: 0.535654
Epoch  500/1000, Cost: 0.489070
Epoch  600/1000, Cost: 0.443538
Epoch  700/1000, Cost: 0.398372
Epoch  800/1000, Cost: 0.353224
Epoch  900/1000, Cost: 0.308175
Epoch 1000/1000, Cost: 0.265126
